# Generated by Django 6.0.1 on 2026-01-11 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 11, 19, 58, 38, 842359, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
