# Generated by Django 4.2.7 on 2026-01-11 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrole',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubrole',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmembershiprequest',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubmembershiprequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_membership_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmembershiprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='faculty_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_advising', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_presiding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clubrole',
            unique_together={('club', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='clubmembershiprequest',
            unique_together={('club', 'user')},
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['status'], name='clubs_club_status_23d2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['category'], name='clubs_club_categor_814472_idx'),
        ),
    ]
